using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Printing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

#pragma warning disable IDE1006
//Fxxk u microsoft ide1006 is the silliest suggestion in all of the ides
//they hate a name which generated by itself
//Damnit

namespace DIYScript_Interpreter {

    public partial class MainForm : Form {

        public MainForm() {
            InitializeComponent();
        }

        public void OBJRefresh() {
            foreach (OBJ obj in GAME.Current.OBJList) {
                listViewOBJ.Clear();
                listViewOBJ.Items.Add(obj.Name, (int)obj.ID);
                //imageList.Images.Add();
            }
        }

        private void 退出ToolStripMenuItem_Click(object sender, EventArgs e) {
            Dispose();
        }

        private void 程序帮助ToolStripMenuItem_Click(object sender, EventArgs e) {

        }

        private void 关于ToolStripMenuItem_Click(object sender, EventArgs e) {
            Form About = new AboutBox();
            About.ShowDialog();
        }


        private void 首选项ToolStripMenuItem_Click(object sender, EventArgs e) {

        }

        private void buttonNewBG_Click(object sender, EventArgs e) {
            openFileDialog.Filter = "位图|*.bmp";
            openFileDialog.FileName = "11145141919810.bmp";
            openFileDialog.ShowDialog();
            buttonRefreshBG.PerformClick();
        }

        private void saveFileDialog_FileOk(object sender, CancelEventArgs e) {
        }

        private void openFileDialog_FileOk(object sender, CancelEventArgs e) {

            BGMaker bGMaker = new BGMaker();
            BGAddingStatus.bitmap = Image.FromFile(openFileDialog.FileName) as Bitmap;
            bGMaker.ShowDialog();
        }
        private void OptionsRefresh() {
            listViewBG.View = listViewOBJ.View = listView1.View = Properties.Settings.Default.LViewValue;

        }
        private void MainForm_Load(object sender, EventArgs e) {
            OBJAddingStatus.CurrentOBJID = 0;
            listViewBG.View = listViewOBJ.View = listView1.View = Properties.Settings.Default.LViewValue;

        }

        private void buttonNewOBJ_Click_1(object sender, EventArgs e) {
            Form OBJ = new OBJMaker();
            OBJ.ShowDialog();
            buttonRefreshOBJ.PerformClick();
        }

        private void richTextBox1_TextChanged(object sender, EventArgs e) {
            
        }

        private void buttonDelOBJ_Click(object sender, EventArgs e) {
            GAME.Current.OBJList.RemoveAt(listViewOBJ.CheckedIndices.Count);
        }

        private void 首选项ToolStripMenuItem_Click_1(object sender, EventArgs e)
        {
            Form options = new Options();
            options.ShowDialog();
            OptionsRefresh();
        }

        private void buttonRefreshOBJ_Click(object sender, EventArgs e)
        {
            listViewOBJ.Clear();
            foreach (OBJ obj in GAME.Current.OBJList)
            {

                listViewOBJ.Items.Add(obj.Name, (int)obj.ID);
                //imageList.Images.Add();
            }
        }


        private void buttonRefreshBG_Click(object sender, EventArgs e)
        {
            listViewBG.Clear();
            imageList2.Images.Clear();
            imageList3.Images.Clear();
            foreach (BG bg in GAME.Current.BGList)
            {                
                imageList2.Images.Add(bg.bitmap);
                imageList3.Images.Add(bg.bitmap);
                listViewBG.Items.Add(bg.Name, (int)bg.ID);

            }
        }

        private void toolStrip_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void buttonDeleteBG_Click(object sender, EventArgs e)
        {
            GAME.Current.DelBG(listViewBG.CheckedIndices.Count);
        }

        private void NUT_Click(object sender, EventArgs e)
        {
            
        }


    }

    public class OBJChoose {
        public static bool isAttach;
        public static OBJ ChoosedOBJ;
    }
    public class OBJArt {
        public Bitmap[] ArtAnimation = new Bitmap[64];
        public int TotalFrames;
        public int CurrentFrame;
    }

    public class GAME {
        public static GAME Current = new GAME();
        public List<OBJ> OBJList = new List<OBJ>();
        public List<BG> BGList = new List<BG>();
        internal void AddOBJ() {
            OBJ OBJ = new OBJ();

            OBJList.Add(OBJ);
        }

        internal void EditOBJ(UInt64 index, string Name, Int16 StartMode, Int16[] SX, Int16[] SY) {
            OBJList[(int)index-1].Name = Name;
            OBJList[(int)index-1].StartMode = StartMode;
            OBJList[(int)index-1].StrtX = SX;
            OBJList[(int)index-1].StrtY = SY;
        }
        internal void DelArt(int index) {
            OBJList.RemoveAt(index);
        }
        internal void AddBG(Bitmap bitmap, string name) {
            BGAddingStatus.CurrentBGID++;
            BG BG = new BG();
            BGList.Add(BG);
            BG.bitmap = bitmap;
            BG.Name = name;
            BG.ID = BGAddingStatus.CurrentBGID;
            BG.Resolution[0] = BGAddingStatus.bitmap.Width;
            BG.Resolution[1] = BGAddingStatus.bitmap.Height;
        }
        internal void DelBG(int index) {
            BGList.RemoveAt(index);
        }
    }
    public class BG {
        public UInt64 ID;
        public Bitmap bitmap;
        public string Name;
        public int[] Resolution = new int[2];
        public void Refresh() {

        }
    }
    public class BGAddingStatus {
        public static UInt64 CurrentBGID=0;
        public static Bitmap bitmap;
    }
    public class OBJAddingStatus {
        public static UInt64 CurrentOBJID=0;

    }
    public class OBJ {
        public UInt64 ID;
        public string Name;
        public Int16 PosX;
        public Int16 PosY;
        public Int16 StartMode;
        // 1 == Location, Point
        // 2 == Location, Area, Anywhere
        // 3 == Location, Area, Try not to overlap
        // 4 == Attath to OBJ
        public Int16[] StrtX = new Int16[2];
        public Int16[] StrtY = new Int16[2];
        // If StartMode == 1, StrtX[] = {x1, x2}, StrtY[] = {y1, y2}
        // If StartMode == 2/3, StrtX[] = {x, null}, StrtY[] = {y, null}
        public UInt64 AttachTargetID;
        public Int16[] AttachOffset = new Int16[2];
        // AttachOffset = {offsetx, offsety}
        public bool[] Switch = new bool[4];
        // Switch A, B, C, D
        public int[] OBJSize = new int[2];
        public OBJArt Arts = new OBJArt();
        public OBJArt CurrentArt;
        public int Rotation = 0;
        public int[] Scale = new int[2];
        // Scale = {XScale, YScale}
        // rotate z axis == decrease scale X axis.
        // Yeah.:)
        public List<OBJArt> ArtList = new List<OBJArt>();

        public void AddArt() {
            OBJArt ART = new OBJArt();
            ArtList.Add(ART);
        }
        public void DelArt(int index) {
            ArtList.RemoveAt(index);
        }

    }
}
