using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#pragma warning disable IDE1006
//Fxxk u microsoft ide1006 is the silliest suggestion in all of the ides
//they hate a name which generated by itself
//Damnit

namespace DIYScript_Interpreter {


    public partial class MainForm : Form {

        public MainForm() {
            InitializeComponent();
        }

        public void OBJRefresh() {
            foreach (OBJ obj in GAME.Current.OBJList) {
                listViewOBJ.Clear();
                listViewOBJ.Items.Add(obj.Name, (int)obj.ID);
                //imageList.Images.Add();
            }
        }

        private void 退出ToolStripMenuItem_Click(object sender, EventArgs e) {
            Dispose();
        }

        private void 程序帮助ToolStripMenuItem_Click(object sender, EventArgs e) {

        }

        private void 关于ToolStripMenuItem_Click(object sender, EventArgs e) {
            Form About = new AboutBox();
            About.ShowDialog();
        }


        private void 首选项ToolStripMenuItem_Click(object sender, EventArgs e) {
            Form options = new Options();
            options.ShowDialog();
            OptionsRefresh();
        }

        private void buttonNewBG_Click(object sender, EventArgs e) {
            openFileDialog.Filter = "位图|*.bmp";
            openFileDialog.FileName = "11145141919810.bmp";
            openFileDialog.ShowDialog();
            buttonRefreshBG.PerformClick();
        }

        private void saveFileDialog_FileOk(object sender, CancelEventArgs e) {
        }

        private void openFileDialog_FileOk(object sender, CancelEventArgs e) {

            BGMaker bGMaker = new BGMaker();
            BGAddingStatus.bitmap = Image.FromFile(openFileDialog.FileName) as Bitmap;
            bGMaker.ShowDialog();
        }
        private void OptionsRefresh() {
            listViewBG.View = listViewOBJ.View = listView1.View = Properties.Settings.Default.LViewValue;

        }
        private void MainForm_Load(object sender, EventArgs e) {
            OBJAddingStatus.CurrentOBJID = 0;
            listViewBG.View = listViewOBJ.View = listView1.View = Properties.Settings.Default.LViewValue;

        }

        private void buttonNewOBJ_Click_1(object sender, EventArgs e) {
            Form OBJ = new OBJMaker();
            OBJ.ShowDialog();
            buttonRefreshOBJ.PerformClick();
        }

        private void richTextBox1_TextChanged(object sender, EventArgs e) {

        }

        private void buttonDelOBJ_Click(object sender, EventArgs e) {
            GAME.Current.OBJList.RemoveAt(listViewOBJ.CheckedIndices.Count);
        }



        private void buttonRefreshOBJ_Click(object sender, EventArgs e) {
            listViewOBJ.Clear();
            foreach (OBJ obj in GAME.Current.OBJList) {

                listViewOBJ.Items.Add(obj.Name, (int)obj.ID);
                //imageList.Images.Add();
            }
        }


        private void buttonRefreshBG_Click(object sender, EventArgs e) {
            listViewBG.Clear();
            imageList2.Images.Clear();
            imageList3.Images.Clear();
            foreach (BG bg in GAME.Current.BGList) {
                imageList2.Images.Add(bg.bitmap);
                imageList3.Images.Add(bg.bitmap);
                listViewBG.Items.Add(bg.Name, (int)bg.ID);

            }
        }

        private void toolStrip_ItemClicked(object sender, ToolStripItemClickedEventArgs e) {

        }

        private void buttonDeleteBG_Click(object sender, EventArgs e) {
            GAME.Current.DelBG(listViewBG.CheckedIndices.Count);
        }

        public void NUT_Click(object sender, EventArgs e) {
            GAME.Current.player.Show();
        }

        private void Run_Click(object sender, EventArgs e) {
            NUT.PerformClick();
        }

        private void buttonAdd_Click(object sender, EventArgs e) {

        }

        private void buttonDel_Click(object sender, EventArgs e) {

        }
    }

}
