using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using static DIYScript_Interpreter.GAME;

#pragma warning disable IDE1006
//Fxxk u microsoft ide1006 is the silliest suggestion in all of the ides
//they hate a name which generated by itself
//Damnit

namespace DIYScript_Interpreter {
    public partial class OBJMaker : Form {
        public OBJMaker() {
            InitializeComponent();
            checkBox1.Enabled = false;// Just for noob :(
        }

        private void OK_Click(object sender, EventArgs e) {
            if (textBoxOBJName.Text == "") {
                errorProvider.SetError(textBoxOBJName, "抄一百遍名字！");

            } else {
                Int16 StartMode = 0;
                if (radioButton1.Checked) {
                    StartMode = 1;
                    //fixed
                } else if (radioButton2.Checked) {
                    if (!checkBox1.Checked) {
                        StartMode = 2;
                        //any
                    } else {
                        StartMode = 3;
                        //not2overlap
                    }
                } else if (OBJChoose.isAttach) {
                    StartMode = 4;
                }
                OBJAddingStatus.CurrentOBJID++;
                GAME.Current.AddOBJ();
                GAME.Current.EditOBJ
                (OBJAddingStatus.CurrentOBJID, textBoxOBJName.Text, StartMode,
                 new Int16[] { (short)trackBar1.Value, (short)trackBar2.Value },
                 new Int16[] { (short)trackBar3.Value, (short)trackBar4.Value });
                Dispose();
            }



        }

        void reDraw(int x1, int y1, int x2, int y2, bool isArea) {
            Bitmap b = new Bitmap(640, 480);
            Point p1 = new Point(x1, y1);
            Graphics g = Graphics.FromImage(b);
            BG NormalBG = Current.BGList.Find(bg => bg.isNormal == true);

            g.DrawImage(NormalBG.bitmap, new Point(0, 0));
            if (isArea) {
                Point p2 = new Point(x2, y2);
                g.DrawRectangle(new Pen(new LinearGradientBrush(new Point((int)Math.Sin(DateTime.Today.Second), (int)Math.Cos(DateTime.Today.Second)), p2, Color.Cyan, Color.Magenta)), p1.X, p1.Y, p2.X - p1.X, p2.Y - p1.Y);
            }
            canvas.Image = b;
        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e) {
            checkBox1.Enabled = radioButton2.Checked;
        }

        private void button2_Click(object sender, EventArgs e) {
            Close();
        }

        private void button1_Click(object sender, EventArgs e) {
            Form OBJChooseForm = new OBJChooser();
            OBJChooseForm.ShowDialog();
        }

        private void OBJMaker_Load(object sender, EventArgs e) {
            listViewART.View = Properties.Settings.Default.LViewValue;
            Bitmap b = new Bitmap(640, 480);
            Graphics g = Graphics.FromImage(b);
            try {
                BG NormalBG = Current.BGList.Find(bg => bg.isNormal == true);

                g.DrawImage(NormalBG.bitmap, new Point(0, 0));
            } catch {

            }

            canvas.Image = b;
        }

        private void buttonNewART_Click(object sender, EventArgs e) {

        }

        private void listViewART_SelectedIndexChanged(object sender, EventArgs e) {

        }

        private void trackBar1_Scroll(object sender, EventArgs e) {

            reDraw(trackBar1.Value, 480 - trackBar3.Value, trackBar2.Value, 480 - trackBar4.Value, radioButton2.Checked);
        }

        private void trackBar2_Scroll(object sender, EventArgs e) {

            reDraw(trackBar1.Value, 480 - trackBar3.Value, trackBar2.Value, 480 - trackBar4.Value, radioButton2.Checked);
        }

        private void trackBar3_Scroll(object sender, EventArgs e) {

            reDraw(trackBar1.Value, 480 - trackBar3.Value, trackBar2.Value, 480 - trackBar4.Value, radioButton2.Checked);
        }

        private void trackBar4_Scroll(object sender, EventArgs e) {

            reDraw(trackBar1.Value, 480 - trackBar3.Value, trackBar2.Value, 480 - trackBar4.Value, radioButton2.Checked);
        }

        private void textBoxOBJName_TextChanged(object sender, EventArgs e) {
            errorProvider.SetError(textBoxOBJName, null);
        }
    }
}
