using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ICSharpCode.TextEditor;
#pragma warning disable IDE1006
//Fxxk u microsoft ide1006 is the silliest suggestion in all of the ides
//they hate a name which generated by itself
//Damnit

namespace DIYScript_Interpreter
{
    public partial class Options : Form
    {

        public Options()
        {
            InitializeComponent();
        }

        private void buttonFont_Click(object sender, EventArgs e)
        {
            fontDialog1.ShowDialog();
            buttonFont.Font = fontDialog1.Font;
            textEditorControl1.Font = fontDialog1.Font;
        }

        private void Options_Load(object sender, EventArgs e)
        {
            Properties.Settings.Default.BackColor = buttonCBG.ForeColor = textEditorControl1.BackColor;
            Properties.Settings.Default.ForeColor = buttonCFront.ForeColor = textEditorControl1.ForeColor;
            Properties.Settings.Default.Font = buttonFont.Font = textEditorControl1.Font;
            Properties.Settings.Default.LineNumber = checkBox1.Checked = textEditorControl1.ShowLineNumbers;
            Properties.Settings.Default.LViewValue = (View)comboBox1.SelectedIndex;
            Properties.Settings.Default.LViewValue = listViewExample.View;
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            listViewExample.View = (View)comboBox1.SelectedIndex;
        }

        private void buttonCFront_Click(object sender, EventArgs e)
        {
            colorDialog1.ShowDialog();
            buttonCFront.ForeColor = colorDialog1.Color;
            textEditorControl1.ForeColor = colorDialog1.Color;
        }

        private void buttonCBG_Click(object sender, EventArgs e)
        {
            colorDialog2.ShowDialog();
            buttonCBG.ForeColor = colorDialog2.Color;
            textEditorControl1.BackColor = colorDialog2.Color;
        }

        private void tabPage1_Click(object sender, EventArgs e)
        {

        }

        private void textEditorControl1_Load(object sender, EventArgs e)
        {

        }

        private void button2_Click(object sender, EventArgs e)
        {
            Properties.Settings.Default.Font = fontDialog1.Font;
            Properties.Settings.Default.ForeColor = colorDialog1.Color;
            Properties.Settings.Default.BackColor = colorDialog2.Color;
            Properties.Settings.Default.LineNumber = checkBox1.Checked;
            Properties.Settings.Default.LViewValue = listViewExample.View;
            Properties.Settings.Default.Save();
        }

        private void button3_Click(object sender, EventArgs e)
        {
            button2.PerformClick();
            Close();
        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            textEditorControl1.ShowLineNumbers = checkBox1.Checked;
        }
    }
}
